;******************************************************************************* 
; AUTHOR: PABLO IZAGUIRRE (PABLO.IZAGUIRRE@ESTUDIANTE.UAM.ES)
;
; THIS CODE PERFORMS A SERIES OF OPERATIONS MOVING DATA FROM THE REGISTERS
; TO THE MEMORY AND VICEVERSA
;*******************************************************************************

; DEFINICION DEL SEGMENTO DE DATOS 

DATOS SEGMENT 

DATOS ENDS 

; DEFINICION DEL SEGMENTO DE PILA 

PILA    SEGMENT STACK "STACK" 
    DB   40H DUP (0) 
PILA ENDS 


; DEFINICION DEL SEGMENTO EXTRA 

EXTRA     SEGMENT 
    RESULT    DW 0,0                 ; 2 PALABRAS ( 4 BYTES ) 
EXTRA ENDS 


; DEFINICION DEL SEGMENTO DE CODIGO 

CODE    SEGMENT 
    ASSUME CS:CODE, DS:DATOS, ES: EXTRA, SS:PILA 

FACT_DATO_1  DW       0 
FACT_DATO_1_DX  DW    0

; COMIENZO DEL PROCEDIMIENTO PRINCIPAL 

START PROC 
    ;INICIALIZA LOS REGISTROS DE SEGMENTO CON SUS VALORES 
    MOV AX, DATOS 
    MOV DS, AX 

    MOV AX, PILA 
    MOV SS, AX 

    MOV AX, EXTRA 
    MOV ES, AX 

    ; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO 
    MOV SP, 64 

    ; FIN DE LAS INICIALIZACIONES 

    MOV AX, 9BH

    MOV BL, 0B2H

    MOV CX, 3412H
    
    MOV AX, 01001001b
    MOV DS, AX

    MOV DX, CX

    MOV AX, 5000H
    MOV DS, AX
    MOV BX, DS:[5235H]

    MOV AX, 7000H
    MOV DS, AX
    MOV DS:[8H], CH

    MOV AX, [SI]

    MOV BX, [BP+10]

    ; FIN DEL PROGRAMA 
    MOV AX, 4C00H 
    INT 21H 

START ENDP

CODE ENDS

END START