;**************************************************************************
; MBS 2021. BASIC STRUCTURE OF AN ASSEMBLER PROGRAMME
; PABLO IZAGUIRRE PABLO.IZAGUIRRE@ESTUDIANTE.UAM.ES
; GROUP 2291
;**************************************************************************

; DATA SEGMENT DEFINITION
DATA SEGMENT
    BOOKMARK    DB  0
    DRINK       DW  0CAFEh
    TABLE200    DB  200 dup(0)
    TOTALERROR1 DB  "This programme always crashes"
DATA ENDS

;**************************************************************************
; STACK SEGMENT DEFINITION
STACKSEG SEGMENT STACK "STACK"
DB 40H DUP (0) ; initialization example, 64 bytes initialize to 0
STACKSEG ENDS

;**************************************************************************
; EXTRA SEGMENT DEFINITION
EXTRA SEGMENT
RESULT DW 0,0 ; initialization example. 2 WORDS (4 BYTES)
EXTRA ENDS

;**************************************************************************
; CODE SEGMENT DEFINITION
CODE SEGMENT
ASSUME CS: CODE, DS: DATA, ES: EXTRA, SS: STACKSEG
; BEGINNING OF MAIN PROCEDURE
BEGIN PROC
    ; INITIALIZE THE SEGMENT REGISTER WITH ITS VALUE
    MOV AX, DATA
    MOV DS, AX
    MOV AX, STACKSEG
    MOV SS, AX
    MOV AX, EXTRA
    MOV ES, AX
    MOV SP, 64 ; LOAD A STACK POINTER WITH THE HIGHEST VALUE
    ; END OF INITIALIZATIONS
    ; BEGINNING OF THE PROGRAMME
    
    
    MOV AH, TOTALERROR1[2]                  ; TOTALERROR1 HAS 1 BYTE PER ELEMENT, THE SAME AS IN TABLE200, SO WE DONT HAVE TO MODIFY THE DATA TYPE
    MOV TABLE200[63H], AH
     
    MOV AX, DRINK                           ; TABLE200 HAS ELMENTS OF ONE BYTE, SO WE HAVE TO CHANGE THE DATA TYPE TO WORD SO THAT IT CAN FIT THE TWO BYTES FROM DRINK 
    MOV WORD PTR TABLE200[23H], AX

    ; NOW IN AH WE HAVE THE MOST SIFNIFICANT BYTE FROM DRINK
    MOV BOOKMARK, AH                        ; SINCE BOOKMARK CAN STORE ONE BYTE, WHICH IS THE SIZE OF AH, WE DON'T HAVE TO CHANGE THE DATA TYPE

    ; END OF THE PROGRAMME
    MOV AX, 4C00H
    INT 21H
BEGIN ENDP
; END OF THE CODE SEGMENT
CODE ENDS
; END OF THE PROGRAMME POINTING OUT WHERE THE EXECUTION BEGINS
END BEGIN 