;******************************************************************************* 
; AUTHOR: PABLO IZAGUIRRE (PABLO.IZAGUIRRE@ESTUDIANTE.UAM.ES)
;
; THIS CODE PERFORMS A SERIES OF OPERATIONS MOVING DATA FROM THE REGISTERS
; TO THE MEMORY AND VICEVERSA
;*******************************************************************************

; DEFINICION DEL SEGMENTO DE DATOS 

DATOS SEGMENT 

    TEXT        DB  "hola caracola esto mide 35 palabras"
    SIZE_TEXT   DB  $ - TEXT
    RESULTADO   DB  100
    PRUEBA      DW  SEG SIZE_TEXT
    TABLA       DB 1,2,3,4,5
    TESS        DB 2 DUP('A', 011H, 0FFH)
    NEGAT       DD -1

DATOS ENDS 

; DEFINICION DEL SEGMENTO DE PILA 

PILA    SEGMENT STACK "STACK" 
    DB   40H DUP (0) 
PILA ENDS 


; DEFINICION DEL SEGMENTO EXTRA 

EXTRA     SEGMENT 

EXTRA ENDS 


; DEFINICION DEL SEGMENTO DE CODIGO 

CODE    SEGMENT 
    ASSUME CS:CODE, DS:DATOS, ES: EXTRA, SS:PILA 


; COMIENZO DEL PROCEDIMIENTO PRINCIPAL 

START PROC 
    ;INICIALIZA LOS REGISTROS DE SEGMENTO CON SUS VALORES 
    MOV AX, DATOS 
    MOV DS, AX 

    MOV AX, PILA 
    MOV SS, AX 

    MOV AX, EXTRA 
    MOV ES, AX 

    ; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO 
    MOV SP, 64 

    ; FIN DE LAS INICIALIZACIONES 

    MOV AX, WORD PTR SIZE_TEXT

    MOV BX, DS: WORD PTR TABLA
    MOV CX, DS: WORD PTR TABLA[0]

    MOV WORD PTR RESULTADO, BX

    MOV AX, WORD PTR TESS[1]

    ; FIN DEL PROGRAMA 
    MOV AX, 4C00H 
    INT 21H 

START ENDP

CODE ENDS

END START